name: Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install poetry
        run: |
          pipx install poetry

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies (with all extras for tests)
        run: |
          poetry install -E all

      - name: Static typing, linter, formatter
        run: |
          poetry run mypy .
          poetry run ruff .
          poetry run black . --check

      - name: Run tests
        run: |
          poetry run pytest --vcr-record=none

  version:
    name: Bump version
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Install poetry
        run: |
          pipx install poetry

      - name: Bump version and tag version
        run: |
          poetry version patch

          git config user.name "Abdulhalim Kara"
          git config user.email "ahalimkara@gmail.com"
          git add .
          git commit --no-verify --message '[skip ci] Bump version to $(poetry version -s)'
          git tag -a "v$(poetry version -s)" -m "Version $(poetry version -s)"
          git push --follow-tags
