name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install poetry
        run: |
          pipx install poetry

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry

      - name: Build
        run: |
          poetry build

      - name: Publish to PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish

      - name: GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
